"""
Report Generator for VulnScanr
"""
import json
import datetime
import os
from src.utils.logger import setup_logger

class ReportGenerator:
    def __init__(self, target_url, verbose=False):
        self.target_url = target_url
        self.verbose = verbose
        self.logger = setup_logger(verbose)
        self.findings = []
        self.scan_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Create reports directory if it doesn't exist
        self.reports_dir = "reports"
        os.makedirs(self.reports_dir, exist_ok=True)

    def add_finding(self, vulnerability_type, payload, url, severity="Medium"):
        """Add a vulnerability finding to the report"""
        finding = {
            "type": vulnerability_type,
            "payload": payload,
            "url": url,
            "severity": severity,
            "timestamp": self.scan_date
        }
        self.findings.append(finding)
        self.logger.debug(f"📝 Added finding: {vulnerability_type}")

    def generate_html_report(self, filename="vulnscanr_report.html"):
        """Generate an HTML report in the reports folder"""
        try:
            # Create filename with timestamp to avoid overwrites
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            base_name = filename.replace(".html", "")
            report_filename = f"{base_name}_{timestamp}.html"
            report_path = os.path.join(self.reports_dir, report_filename)
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <title>VulnScanr Security Report</title>
                <style>
                    body {{ font-family: Arial, sans-serif; margin: 20px; }}
                    .header {{ background: #f4f4f4; padding: 20px; border-radius: 5px; }}
                    .finding {{ border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }}
                    .critical {{ border-left: 5px solid #ff4444; }}
                    .high {{ border-left: 5px solid #ff8800; }}
                    .medium {{ border-left: 5px solid #ffcc00; }}
                    .low {{ border-left: 5px solid #00cc66; }}
                    .count {{ font-size: 1.2em; font-weight: bold; margin: 10px 0; }}
                    .summary {{ background: #e8f4fd; padding: 15px; border-radius: 5px; margin: 20px 0; }}
                    code {{ background: #f4f4f4; padding: 2px 5px; border-radius: 3px; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>🔍 VulnScanr Security Report</h1>
                    <p><strong>Target:</strong> {self.target_url}</p>
                    <p><strong>Scan Date:</strong> {self.scan_date}</p>
                    <p><strong>Total Findings:</strong> {len(self.findings)}</p>
                </div>
                
                <div class="summary">
                    <h2>📊 Scan Summary</h2>
                    <p><strong>Scan Date:</strong> {self.scan_date}</p>
                    <p><strong>Target URL:</strong> {self.target_url}</p>
                    <p><strong>Total Vulnerabilities Found:</strong> {len(self.findings)}</p>
                    
                    <!-- Vulnerability Breakdown -->
                    <h3>Vulnerability Breakdown:</h3>
            """
            
            # Count vulnerabilities by type
            vuln_counts = {}
            for finding in self.findings:
                vuln_type = finding['type']
                vuln_counts[vuln_type] = vuln_counts.get(vuln_type, 0) + 1
            
            for vuln_type, count in vuln_counts.items():
                html_content += f"<p><strong>{vuln_type}:</strong> {count}</p>"
            
            html_content += f"""
                </div>
                
                <div class="count">
                    📋 Detailed Findings ({len(self.findings)} vulnerabilities):
                </div>
            """

            for i, finding in enumerate(self.findings, 1):
                severity_class = finding['severity'].lower()
                html_content += f"""
                <div class="finding {severity_class}">
                    <h3>🚨 #{i}: {finding['type']} - {finding['severity']} Severity</h3>
                    <p><strong>Payload:</strong> <code>{finding['payload']}</code></p>
                    <p><strong>URL:</strong> {finding['url']}</p>
                    <p><strong>Time:</strong> {finding['timestamp']}</p>
                </div>
                """

            html_content += f"""
                <div class="summary">
                    <h3>📝 Report Information</h3>
                    <p><strong>Generated by:</strong> VulnScanr - Web Vulnerability Scanner</p>
                    <p><strong>Report File:</strong> {report_filename}</p>
                    <p><strong>Note:</strong> This report was automatically generated for security assessment purposes.</p>
                </div>
            </body>
            </html>
            """

            with open(report_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            self.logger.info(f"📄 HTML report generated: {report_path}")
            return report_path

        except Exception as e:
            self.logger.error(f"❌ Failed to generate HTML report: {str(e)}")
            return None

    def generate_json_report(self, filename="vulnscanr_report.json"):
        """Generate a JSON report in the reports folder"""
        try:
            # Create filename with timestamp to avoid overwrites
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            base_name = filename.replace(".json", "")
            report_filename = f"{base_name}_{timestamp}.json"
            report_path = os.path.join(self.reports_dir, report_filename)
            
            report_data = {
                "scan_info": {
                    "scanner": "VulnScanr",
                    "version": "1.0",
                    "target": self.target_url,
                    "scan_date": self.scan_date,
                    "total_findings": len(self.findings)
                },
                "summary": {
                    "total_vulnerabilities": len(self.findings),
                    "vulnerability_breakdown": {}
                },
                "findings": self.findings
            }

            # Add vulnerability breakdown
            for finding in self.findings:
                vuln_type = finding['type']
                if vuln_type not in report_data["summary"]["vulnerability_breakdown"]:
                    report_data["summary"]["vulnerability_breakdown"][vuln_type] = 0
                report_data["summary"]["vulnerability_breakdown"][vuln_type] += 1

            with open(report_path, 'w', encoding='utf-8') as f:
                json.dump(report_data, f, indent=2)
            
            self.logger.info(f"📄 JSON report generated: {report_path}")
            return report_path

        except Exception as e:
            self.logger.error(f"❌ Failed to generate JSON report: {str(e)}")
            return None

    def generate_text_summary(self):
        """Generate a quick text summary in the console"""
        if not self.findings:
            return "No vulnerabilities found."
        
        summary = f"""
📊 VULNSCANR SCAN SUMMARY
────────────────────────
Target: {self.target_url}
Scan Date: {self.scan_date}
Total Findings: {len(self.findings)}

VULNERABILITY BREAKDOWN:
"""
        # Count vulnerabilities by type
        vuln_counts = {}
        for finding in self.findings:
            vuln_type = finding['type']
            vuln_counts[vuln_type] = vuln_counts.get(vuln_type, 0) + 1
        
        for vuln_type, count in vuln_counts.items():
            summary += f"  • {vuln_type}: {count}\n"
        
        summary += f"\nReports saved to: {self.reports_dir}/"
        return summary